apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
data:
  username: YXBw
  password: QnBURVhUakdjN1BGQnZXdjlmSHo=
  host: ZGF0YWJhc2Utc2VydmljZQ==
  port: NTQzMg==
  dbname: YXBw
  connectionString: cG9zdGdyZXNxbDovL2FwcDpCcFRFWFRqR2M3UEZCdld2OWZIekBkYXRhYmFzZS1zZXJ2aWNlOjU0MzIvYXBwP3NlcnZlclZlcnNpb249MTUmY2hhcnNldD11dGY4
